apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: forecastify-prod
  labels:
    app.kubernetes.io/name: forecastify-frontend
    app.kubernetes.io/part-of: forecastify-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api
  namespace: forecastify-prod
  labels:
    app.kubernetes.io/name: forecastify-api
    app.kubernetes.io/part-of: forecastify-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-jarvis
  namespace: forecastify-prod
  labels:
    app.kubernetes.io/name: forecastify-jarvis
    app.kubernetes.io/part-of: forecastify-platform
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forecastify-read-config-role
  namespace: forecastify-prod
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forecastify-api-read-config-binding
  namespace: forecastify-prod
subjects:
- kind: ServiceAccount
  name: sa-api
  namespace: forecastify-prod
roleRef:
  kind: Role
  name: forecastify-read-config-role
  apiGroup: rbac.authorization.k8s.io
