apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forecastify-prod

resources:
  - namespace.yaml
  - configmaps/app-config.yaml
  - rbac/serviceaccounts.yaml
  - networkpolicies/default-deny.yaml
  - networkpolicies/component-policies.yaml
  - quotas/resource-quota.yaml
  - priorityclasses/priority-classes.yaml
  - frontend/deployment.yaml
  - api/deployment.yaml
  - jarvis/deployment.yaml
  - ingress/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: forecastify-platform
  app.kubernetes.io/managed-by: kustomize
