apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: forecastify-secret-store
  namespace: forecastify-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: sa-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forecastify-external-secrets
  namespace: forecastify-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: forecastify-secret-store
    kind: SecretStore
  target:
    name: forecastify-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_SUPABASE_URL
      remoteRef:
        key: forecastify/prod/supabase
        property: url
    - secretKey: NEXT_PUBLIC_SUPABASE_ANON_KEY
      remoteRef:
        key: forecastify/prod/supabase
        property: anonKey
    - secretKey: GROQ_API_KEY
      remoteRef:
        key: forecastify/prod/groq
        property: apiKey
    - secretKey: GROQ_API_KEY_2
      remoteRef:
        key: forecastify/prod/groq
        property: apiKey2
    - secretKey: GROQ_API_KEY_3
      remoteRef:
        key: forecastify/prod/groq
        property: apiKey3
    - secretKey: SERPER_API_KEY
      remoteRef:
        key: forecastify/prod/serper
        property: apiKey
    - secretKey: OPENWEATHER_API_KEY
      remoteRef:
        key: forecastify/prod/openweather
        property: apiKey
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: forecastify/prod/gemini
        property: apiKey
